# Generated by Django 3.1.6 on 2024-03-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_labour_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
