# Generated by Django 3.1.6 on 2024-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_auto_20240313_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='cost_per_day',
            field=models.FloatField(default=0.0),
        ),
    ]
